import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import UserContextProvider from "@/context/UserContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PANKH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
        </UserContextProvider>
      </body>
    </html>
  );
}
